# Generated by Django 5.2.16 on 2026-09-06 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0036_merge_20260905_1122'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MALAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_username', models.CharField(blank=True, default='', max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('sync_enabled', models.BooleanField(default=True)),
                ('connection_broken', models.BooleanField(default=False, help_text='True once MyAnimeList rejects the refresh token, until reconnected')),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mal_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MyAnimeList account',
            },
        ),
    ]
