# Generated by Django 5.2.16 on 2026-09-12 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0037_malaccount'),
        ('integrations', '0047_merge_20260910_1141'),
    ]

    operations = [
    ]
