# Generated by Django 5.2.16 on 2026-09-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0049_plexaccount_mark_watched_sync'),
        ('integrations', '0053_malaccount_pull_ratings_enabled'),
    ]

    operations = [
    ]
