# Generated by Django 5.2.16 on 2026-09-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0054_merge_20260925_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='malaccount',
            name='sync_filter_paused',
            field=models.BooleanField(default=False, help_text='Include Paused entries in a full sync to MyAnimeList'),
        ),
        migrations.AddField(
            model_name='malaccount',
            name='sync_filter_planning',
            field=models.BooleanField(default=False, help_text='Include Planning entries in a full sync to MyAnimeList'),
        ),
    ]
