# Generated by Django 5.2.16 on 2026-10-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0052_merge_20261001_1051'),
        ('integrations', '0057_oauthrefreshtoken_replaced_by'),
    ]

    operations = [
    ]
