# Generated by Django 5.2.16 on 2026-10-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0058_merge_20261006_1616'),
        ('integrations', '0058_psn_playtime_snapshots'),
    ]

    operations = [
    ]
