# Generated by Django 5.2.16 on 2026-10-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0138_merge_20261001_1051'),
        ('users', '0148_list_detail_tier_options'),
    ]

    operations = [
    ]
